### ISSUE TITLE
通过javaAdapter实现接口会内存泄露

### ISSUE THREAD

**Issue by yikus-tjq** [SuperMonster003/AutoJs6#110]
![Screenshot_2023-07-21-17-43-48-209_com miui bugreport](https://github.com/SuperMonster003/AutoJs6/assets/38431925/0ab551dd-1849-4110-96dc-4ec40a6a7dde)
运行代码直接闪退这个是手机给出来的错误日志，手机：小米9，安卓10

具体报错：
java.lang.StackOverflowError: stack size 8192KB
	at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:734)
	at org.autojs.autojs.rhino.AndroidClassLoader.loadClass(AndroidClassLoader.kt:101)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:367)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at org.autojs.autojs.rhino.AndroidClassLoader.loadClass(AndroidClassLoader.kt:103)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:367)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at org.autojs.autojs.rhino.AndroidClassLoader.loadClass(AndroidClassLoader.kt:103)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:367)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at org.autojs.autojs.rhino.AndroidClassLoader.loadClass(AndroidClassLoader.kt:103)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:367)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at org.autojs.autojs.rhino.AndroidClassLoader.loadClass(AndroidClassLoader.kt:103)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:367)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at org.autojs.autojs.rhino.AndroidClassLoader.loadClass(AndroidClassLoader.kt:103)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:367)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at org.autojs.autojs.rhino.AndroidClassLoader.loadClass(AndroidClassLoader.kt:103)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:367)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at org.autojs.autojs.rhino.AndroidClassLoader.loadClass(AndroidClassLoader.kt:103)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:367)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at org.autojs.autojs.rhino.AndroidClassLoader.loadClass(AndroidClassLoader.kt:103)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:367)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at org.autojs.autojs.rhino.AndroidClassLoader.loadClass(AndroidClassLoader.kt:103)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:367)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at org.autojs.autojs.rhino.AndroidClassLoader.loadClass(AndroidClassLoader.kt:103)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:367)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at org.autojs.autojs.rhino.AndroidClassLoader.loadClass(AndroidClassLoader.kt:103)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:367)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at org.autojs.autojs.rhino.AndroidClassLoader.loadClass(AndroidClassLoader.kt:103)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:367)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at org.autojs.autojs.rhino.AndroidClassLoader.loadClass(AndroidClassLoader.kt:103)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:367)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at org.autojs.autojs.rhino.AndroidClassLoader.loadClass(AndroidClassLoader.kt:103)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:367)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at org.autojs.autojs.rhino.AndroidClassLoader.loadClass(AndroidClassLoader.kt:103)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:367)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at org.autojs.autojs.rhino.AndroidClassLoader.loadClass(AndroidClassLoader.kt:103)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:367)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at org.autojs.autojs.rhino.AndroidClassLoader.loadClass(AndroidClassLoader.kt:103)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:367)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at org.autojs.autojs.rhino.AndroidClassLoader.loadClass(AndroidClassLoader.kt:103)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:367)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at org.autojs.autojs.rhino.AndroidClassLoader.loadClass(AndroidClassLoader.kt:103)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:367)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at org.autojs.autojs.rhino.AndroidClassLoader.loadClass(AndroidClassLoader.kt:103)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:367)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at org.autojs.autojs.rhino.AndroidClassLoader.loadClass(AndroidClassLoader.kt:103)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:367)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at org.autojs.autojs.rhino.AndroidClassLoader.loadClass(AndroidClassLoader.kt:103)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:367)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at org.autojs.autojs.rhino.AndroidClassLoader.loadClass(AndroidClassLoader.kt:103)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:367)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at org.autojs.autojs.rhino.AndroidClassLoader.loadClass(AndroidClassLoader.kt:103)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:367)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at org.autojs.autojs.rhino.AndroidClassLoader.loadClass(AndroidClassLoader.kt:103)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:367)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at org.autojs.autojs.rhino.AndroidClassLoader.loadClass(AndroidClassLoader.kt:103)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:367)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at org.autojs.autojs.rhino.AndroidClassLoader.loadClass(AndroidClassLoader.kt:103)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:367)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at org.autojs.autojs.rhino.AndroidClassLoader.loadClass(AndroidClassLoader.kt:103)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:367)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at org.autojs.autojs.rhino.AndroidClassLoader.loadClass(AndroidClassLoader.kt:103)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:367)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at org.autojs.autojs.rhino.AndroidClassLoader.loadClass(AndroidClassLoader.kt:103)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:367)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at org.autojs.autojs.rhino.AndroidClassLoader.loadClass(AndroidClassLoader.kt:103)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:367)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at org.autojs.autojs.rhino.AndroidClassLoader.loadClass(AndroidClassLoader.kt:103)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:367)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at org.autojs.autojs.rhino.AndroidClassLoader.loadClass(AndroidClassLoader.kt:103)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:367)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at org.autojs.autojs.rhino.AndroidClassLoader.loadClass(AndroidClassLoader.kt:103)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:367)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at org.autojs.autojs.rhino.AndroidClassLoader.loadClass(AndroidClassLoader.kt:103)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:367)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at org.autojs.autojs.rhino.AndroidClassLoader.loadClass(AndroidClassLoader.kt:103)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:367)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at org.autojs.autojs.rhino.AndroidClassLoader.loadClass(AndroidClassLoader.kt:103)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:367)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at org.autojs.autojs.rhino.AndroidClassLoader.loadClass(AndroidClassLoader.kt:103)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:367)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at org.autojs.autojs.rhino.AndroidClassLoader.loadClass(AndroidClassLoader.kt:103)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:367)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at org.autojs.autojs.rhino.AndroidClassLoader.loadClass(AndroidClassLoader.kt:103)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:367)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at org.autojs.autojs.rhino.AndroidClassLoader.loadClass(AndroidClassLoader.kt:103)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:367)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at org.autojs.autojs.rhino.AndroidClassLoader.loadClass(AndroidClassLoader.kt:103)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:367)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at org.autojs.autojs.rhino.AndroidClassLoader.loadClass(AndroidClassLoader.kt:103)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:367)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at org.autojs.autojs.rhino.AndroidClassLoader.loadClass(AndroidClassLoader.kt:103)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:367)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at org.autojs.autojs.rhino.AndroidClassLoader.loadClass(AndroidClassLoader.kt:103)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:367)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at org.autojs.autojs.rhino.AndroidClassLoader.loadClass(AndroidClassLoader.kt:103)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:367)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at org.autojs.autojs.rhino.AndroidClassLoader.loadClass(AndroidClassLoader.kt:103)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:367)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at org.autojs.autojs.rhino.AndroidClassLoader.loadClass(AndroidClassLoader.kt:103)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:367)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at org.autojs.autojs.rhino.AndroidClassLoader.loadClass(AndroidClassLoader.kt:103)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:367)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at org.autojs.autojs.rhino.AndroidClassLoader.loadClass(AndroidClassLoader.kt:103)
	at java.lang.ClassLoader.loadClass(ClassLoa
[TRUNCATED 8015450 CHARS]
ClassLoader.java:312)
	at org.autojs.autojs.rhino.AndroidClassLoader.loadClass(AndroidClassLoader.kt:103)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:367)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at org.autojs.autojs.rhino.AndroidClassLoader.loadClass(AndroidClassLoader.kt:103)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:367)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at org.autojs.autojs.rhino.AndroidClassLoader.loadClass(AndroidClassLoader.kt:103)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:367)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at org.autojs.autojs.rhino.AndroidClassLoader.loadClass(AndroidClassLoader.kt:103)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:367)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at org.autojs.autojs.rhino.AndroidClassLoader.loadClass(AndroidClassLoader.kt:103)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:367)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at org.autojs.autojs.rhino.AndroidClassLoader.loadClass(AndroidClassLoader.kt:103)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:367)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at org.autojs.autojs.rhino.AndroidClassLoader.loadClass(AndroidClassLoader.kt:103)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:367)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at org.autojs.autojs.rhino.AndroidClassLoader.loadClass(AndroidClassLoader.kt:103)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:367)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at org.autojs.autojs.rhino.AndroidClassLoader.loadClass(AndroidClassLoader.kt:103)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:367)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at org.autojs.autojs.rhino.AndroidClassLoader.loadClass(AndroidClassLoader.kt:103)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:367)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at org.autojs.autojs.rhino.AndroidClassLoader.loadClass(AndroidClassLoader.kt:103)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:367)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at org.autojs.autojs.rhino.AndroidClassLoader.loadClass(AndroidClassLoader.kt:103)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:367)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at org.autojs.autojs.rhino.AndroidClassLoader.loadClass(AndroidClassLoader.kt:103)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:367)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at org.autojs.autojs.rhino.AndroidClassLoader.loadClass(AndroidClassLoader.kt:103)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:367)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at org.autojs.autojs.rhino.AndroidClassLoader.loadClass(AndroidClassLoader.kt:103)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:367)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at org.autojs.autojs.rhino.AndroidClassLoader.loadClass(AndroidClassLoader.kt:103)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:367)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at org.autojs.autojs.rhino.AndroidClassLoader.loadClass(AndroidClassLoader.kt:103)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:367)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at org.autojs.autojs.rhino.AndroidClassLoader.loadClass(AndroidClassLoader.kt:103)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:367)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at org.autojs.autojs.rhino.AndroidClassLoader.loadClass(AndroidClassLoader.kt:103)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:367)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at org.autojs.autojs.rhino.AndroidClassLoader.loadClass(AndroidClassLoader.kt:103)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:367)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at org.autojs.autojs.rhino.AndroidClassLoader.loadClass(AndroidClassLoader.kt:103)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:367)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at org.autojs.autojs.rhino.AndroidClassLoader.loadClass(AndroidClassLoader.kt:103)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:367)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at org.autojs.autojs.rhino.AndroidClassLoader.loadClass(AndroidClassLoader.kt:103)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:367)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at org.autojs.autojs.rhino.AndroidClassLoader.loadClass(AndroidClassLoader.kt:103)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:367)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at org.autojs.autojs.rhino.AndroidClassLoader.loadClass(AndroidClassLoader.kt:103)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:367)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at org.autojs.autojs.rhino.AndroidClassLoader.loadClass(AndroidClassLoader.kt:103)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:367)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at org.autojs.autojs.rhino.AndroidClassLoader.loadClass(AndroidClassLoader.kt:103)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:367)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at org.autojs.autojs.rhino.AndroidClassLoader.loadClass(AndroidClassLoader.kt:103)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:367)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at org.autojs.autojs.rhino.AndroidClassLoader.loadClass(AndroidClassLoader.kt:103)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:367)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at org.autojs.autojs.rhino.AndroidClassLoader.loadClass(AndroidClassLoader.kt:103)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:367)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at org.autojs.autojs.rhino.AndroidClassLoader.loadClass(AndroidClassLoader.kt:103)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:367)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at org.autojs.autojs.rhino.AndroidClassLoader.loadClass(AndroidClassLoader.kt:103)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:367)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at org.autojs.autojs.rhino.AndroidClassLoader.loadClass(AndroidClassLoader.kt:103)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:367)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at org.autojs.autojs.rhino.AndroidClassLoader.loadClass(AndroidClassLoader.kt:103)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:367)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at org.autojs.autojs.rhino.AndroidClassLoader.loadClass(AndroidClassLoader.kt:103)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:367)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at org.autojs.autojs.rhino.AndroidClassLoader.loadClass(AndroidClassLoader.kt:103)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:367)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at org.autojs.autojs.rhino.AndroidClassLoader.loadClass(AndroidClassLoader.kt:103)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:367)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at org.autojs.autojs.rhino.AndroidClassLoader.loadClass(AndroidClassLoader.kt:103)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:367)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at org.autojs.autojs.rhino.AndroidClassLoader.loadClass(AndroidClassLoader.kt:103)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:367)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at org.autojs.autojs.rhino.AndroidClassLoader.loadClass(AndroidClassLoader.kt:103)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:367)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at org.autojs.autojs.rhino.AndroidClassLoader.loadClass(AndroidClassLoader.kt:103)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:367)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at org.autojs.autojs.rhino.AndroidClassLoader.defineClass(AndroidClassLoader.kt:131)
	at org.mozilla.javascript.JavaAdapter.loadAdapterClass(JavaAdapter.java:504)
	at org.mozilla.javascript.JavaAdapter.getAdapterClass(JavaAdapter.java:311)
	at org.mozilla.javascript.JavaAdapter.js_createAdapter(JavaAdapter.java:166)
	at org.mozilla.javascript.JavaAdapter.execIdCall(JavaAdapter.java:84)
	at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:84)
	at org.mozilla.javascript.BaseFunction.construct(BaseFunction.java:402)
	at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1931)
	at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:1051)
	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:87)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:383)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3869)
	at org.mozilla.javascript.InterpretedFunction.exec(InterpretedFunction.java:100)
	at org.autojs.autojs.engine.RhinoJavaScriptEngine.doExecution(RhinoJavaScriptEngine.kt:77)
	at org.autojs.autojs.engine.JavaScriptEngine.execute(JavaScriptEngine.java:24)
	at org.autojs.autojs.engine.LoopBasedJavaScriptEngine.access$001(LoopBasedJavaScriptEngine.java:16)
	at org.autojs.autojs.engine.LoopBasedJavaScriptEngine.lambda$execute$0(LoopBasedJavaScriptEngine.java:41)
	at org.autojs.autojs.engine.LoopBasedJavaScriptEngine.$r8$lambda$I-xFIUoHN3n1hvGjYIMvKioppEM(Unknown Source:0)
	at org.autojs.autojs.engine.LoopBasedJavaScriptEngine$$ExternalSyntheticLambda0.run(Unknown Source:6)
	at android.os.Handler.handleCallback(Handler.java:914)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:238)
	at android.app.ActivityThread.main(ActivityThread.java:7619)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by yikus-tjq** [comment]
autojs6版本：6.3.2

**Comment by SuperMonster003** [comment]
#99
