### ISSUE TITLE
通讯录添加联系人应该怎么实现？

### ISSUE THREAD

**Issue by photkey** [SuperMonster003/AutoJs6#111]
下面是从网上查的autojs 通讯录添加联系人的实现方法，但是在autojs6里面运行不了，请问下autojs6中应该如何实现添加联系人的功能？
```
// 写入通讯录单个联系人
function writeContct(phone, name) {
    var a = new android.content.ContentValues();
    a.put("account_type", android.accounts.AccountManager.KEY_ACCOUNT_TYPE);
    a.put("account_name", android.accounts.AccountManager.KEY_ACCOUNT_NAME);

    var rawContactUri = context.getContentResolver().insert(android.provider.ContactsContract.RawContacts.CONTENT_URI, a);
    var rawContactId = android.content.ContentUris.parseId(rawContactUri)

    var b = new android.content.ContentValues();
    b['put(java.lang.String,java.lang.Long)']("raw_contact_id", rawContactId);
    b.put("mimetype", "vnd.android.cursor.item/name");
    b.put("data1", name);
    context.getContentResolver().insert(android.provider.ContactsContract.Data.CONTENT_URI, b);

    var c = new android.content.ContentValues();
    c['put(java.lang.String,java.lang.Long)']("raw_contact_id", rawContactId);
    c.put("mimetype", "vnd.android.cursor.item/phone_v2");
    c.put("data1", phone);
    c["put(java.lang.String,java.lang.Integer)"]("data2", 2);
    context.getContentResolver().insert(android.provider.ContactsContract.Data.CONTENT_URI, c);
}

// 清空通讯录所有联系人
function cleanContact() {
    var ContentProviderOperation = android.content.ContentProviderOperation;
    var rawUri = android.provider.ContactsContract.Data.CONTENT_URI.buildUpon().appendQueryParameter("caller_is_syncadapter", "true").build();
    var ops = new java.util.ArrayList();
    var array = java.lang.reflect.Array.newInstance(java.lang.String, 1);
    array[0] = "-1";
    ops.add(ContentProviderOperation.newDelete(android.provider.ContactsContract.Data.CONTENT_URI).withSelection("_id>? ", array).build()) //sets deleted flag to 1
    ops.add(ContentProviderOperation.newDelete(rawUri).withSelection("_id>? ", array).build()) //erases
    context.getContentResolver().applyBatch("com.android.contacts", ops);
}
```

以下是这段代码在autojs6中运行的报错信息：
```
15:38:43.122/V: 开始运行 [$cwd/modules/Contct.js].
15:38:43.142/E: Wrapped java.lang.SecurityException: Permission Denial: opening provider com.android.providers.contacts.ContactsProvider2 from ProcessRecord{d29617f 925:org.autojs.autojs6/u0a56} (pid=925, uid=10056) requires android.permission.READ_CONTACTS or android.permission.WRITE_CONTACTS (/storage/emulated/0/Download/脚本/modules/Contct.js#7)
Wrapped java.lang.SecurityException: Permission Denial: opening provider com.android.providers.contacts.ContactsProvider2 from ProcessRecord{d29617f 925:org.autojs.autojs6/u0a56} (pid=925, uid=10056) requires android.permission.READ_CONTACTS or android.permission.WRITE_CONTACTS
    at writeContct (/storage/emulated/0/Download/脚本/modules/Contct.js:7:0)
    at /storage/emulated/0/Download/脚本/modules/Contct.js:37:0

15:38:43.146/V: [$cwd/modules/Contct.js] 运行结束 (用时 0.020 秒)

```

**Comment by SuperMonster003** [comment]
读写联系人是非常危险且设计用户隐私的权限, 更可能出现恶意写入联系人信息的行为.

因此 AutoJs6 暂不提供与联系人相关的权限开放, 也无法使用联系人相关的 API.
