### ISSUE TITLE
偶尔崩溃

### ISSUE THREAD

**Issue by wingswing1** [SuperMonster003/AutoJs6#121]
可能和系统有关，是MIUI14安卓13，偶尔崩溃
抓到了部分日志：
07:30:52.864/E: Failed to allocate a 80 byte allocation with 1669024 free bytes and 1629KB until OOM, target footprint 536870912, growth limit 536870912; giving up on allocation because <1% of heap free after GC.

java.lang.OutOfMemoryError: Failed to allocate a 80 byte allocation with 1669024 free bytes and 1629KB until OOM, target footprint 536870912, growth limit 536870912; giving up on allocation because <1% of heap free after GC.
	at org.mozilla.javascript.JavaMembers.reflect(JavaMembers.java:467)
	at org.mozilla.javascript.JavaMembers.<init>(JavaMembers.java:56)
	at org.mozilla.javascript.JavaMembers_jdk11.<init>(JavaMembers_jdk11.java:18)
	at org.mozilla.javascript.JavaMembers.createJavaMembers(JavaMembers.java:827)
	at org.mozilla.javascript.JavaMembers.lookupClass(JavaMembers.java:788)
	at org.mozilla.javascript.NativeJavaClass.initMembers(NativeJavaClass.java:44)
	at org.mozilla.javascript.NativeJavaObject.<init>(NativeJavaObject.java:53)
	at org.mozilla.javascript.NativeJavaClass.<init>(NativeJavaClass.java:38)
	at org.mozilla.javascript.NativeJavaClass.<init>(NativeJavaClass.java:34)
	at org.mozilla.javascript.WrapFactory.wrapJavaClass(WrapFactory.java:136)
	at org.mozilla.javascript.NativeJavaPackage.getPkgProperty(NativeJavaPackage.java:115)
	at org.mozilla.javascript.NativeJavaPackage.get(NativeJavaPackage.java:72)
	at org.mozilla.javascript.ScriptableObject.getProperty(ScriptableObject.java:2024)
	at org.mozilla.javascript.ScriptRuntime.getObjectProp(ScriptRuntime.java:1671)
	at org.mozilla.javascript.ScriptRuntime.getObjectProp(ScriptRuntime.java:1666)
	at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1549)
	at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:1051)
	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:87)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:383)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3869)
	at org.mozilla.javascript.Context.callFunctionWithContinuations(Context.java:1253)
	at org.mozilla.javascript.Context.executeScriptWithContinuations(Context.java:1221)
	at org.autojs.autojs.engine.RhinoJavaScriptEngine.init(RhinoJavaScriptEngine.kt:110)
	at org.autojs.autojs.engine.LoopBasedJavaScriptEngine.init(LoopBasedJavaScriptEngine.java:101)
	at org.autojs.autojs.execution.RunnableScriptExecution.prepare(RunnableScriptExecution.java:65)
	at org.autojs.autojs.execution.RunnableScriptExecution.execute(RunnableScriptExecution.java:39)
	at org.autojs.autojs.execution.RunnableScriptExecution.execute(RunnableScriptExecution.java:34)
	at org.autojs.autojs.execution.RunnableScriptExecution.run(RunnableScriptExecution.java:28)
	at java.lang.Thread.run(Thread.java:1012)
07:30:52.866/E: exception on exit: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean org.autojs.autojs.runtime.api.Events.emit(java.lang.String, java.lang.Object[])' on a null object reference

**Comment by CuteLicense** [comment]
内存溢出，是不是在重复处理图片，处理后没有及时释放

**Comment by wingswing1** [comment]
没有处理图片呀，就是简单的打开app找控件签到，而且不是每次崩溃，是偶尔。不知道是什么引起的



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年08月10日 09:06 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [SuperMonster003/AutoJs6] 偶尔崩溃 (Issue #121) |

内存溢出，是不是在重复处理图片，处理后没有及时释放

**Comment by SuperMonster003** [comment]
https://github.com/SuperMonster003/AutoJs6/issues/148
