### ISSUE TITLE
Stack Over Flow

### ISSUE THREAD

**Issue by anhnhoktvn** [SuperMonster003/AutoJs6#141]
I think there is a problem with http module.
```
  for (let i = 0; i < 6e3; i++) {
    console.log(i)
    // change to a local http server to make it run faster
    http.postJson('https://httpbin.org/post').body.string()
  }
  ```
  It can not run more than 4k request
  
  ```
  12:54:29.738/D: 3409
12:54:30.004/D: 3410
12:54:30.293/D: 3411
12:54:30.933/E: stack size 1039KB

java.lang.StackOverflowError: stack size 1039KB
	at okhttp3.internal.http2.Http2ExchangeCodec.cancel(Unknown Source:0)
	at okhttp3.internal.connection.Exchange.detachWithViolence(Exchange.kt:166)
	at okhttp3.internal.connection.RealCall.exitNetworkInterceptorExchange$okhttp(RealCall.kt:437)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:110)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at org.autojs.autojs.core.http.MutableOkHttp.mRetryInterceptor$lambda$1(MutableOkHttp.kt:26)
	at org.autojs.autojs.core.http.MutableOkHttp.$r8$lambda$I8T0L3HXiktX77DhmwsSju4W-dc(Unknown Source:0)
	at org.autojs.autojs.core.http.MutableOkHttp$$ExternalSyntheticLambda0.intercept(Unknown Source:2)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at org.autojs.autojs.core.http.MutableOkHttp.mRetryInterceptor$lambda$1(MutableOkHttp.kt:26)
	at org.autojs.autojs.core.http.MutableOkHttp.$r8$lambda$I8T0L3HXiktX77DhmwsSju4W-dc(Unknown Source:0)
	at org.autojs.autojs.core.http.MutableOkHttp$$ExternalSyntheticLambda0.intercept(Unknown Source:2)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at org.autojs.autojs.core.http.MutableOkHttp.mRetryInterceptor$lambda$1(MutableOkHttp.kt:26)
	at org.autojs.autojs.core.http.MutableOkHttp.$r8$lambda$I8T0L3HXiktX77DhmwsSju4W-dc(Unknown Source:0)
	at org.autojs.autojs.core.http.MutableOkHttp$$ExternalSyntheticLambda0.intercept(Unknown Source:2)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at org.autojs.autojs.core.http.MutableOkHttp.mRetryInterceptor$lambda$1(MutableOkHttp.kt:26)
	at org.autojs.autojs.core.http.MutableOkHttp.$r8$lambda$I8T0L3HXiktX77DhmwsSju4W-dc(Unknown Source:0)
	at org.autojs.autojs.core.http.MutableOkHttp$$ExternalSyntheticLambda0.intercept(Unknown Source:2)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at org.autojs.autojs.core.http.MutableOkHttp.mRetryInterceptor$lambda$1(MutableOkHttp.kt:26)
	at org.autojs.autojs.core.http.MutableOkHttp.$r8$lambda$I8T0L3HXiktX77DhmwsSju4W-dc(Unknown Source:0)
	at org.autojs.autojs.core.http.MutableOkHttp$$ExternalSyntheticLambda0.intercept(Unknown Source:2)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at org.autojs.autojs.core.http.MutableOkHttp.mRetryInterceptor$lambda$1(MutableOkHttp.kt:26)
	at org.autojs.autojs.core.http.MutableOkHttp.$r8$lambda$I8T0L3HXiktX77DhmwsSju4W-dc(Unknown Source:0)
	at org.autojs.autojs.core.http.MutableOkHttp$$ExternalSyntheticLambda0.intercept(Unknown Source:2)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at org.autojs.autojs.core.http.MutableOkHttp.mRetryInterceptor$lambda$1(MutableOkHttp.kt:26)
	at org.autojs.autojs.core.http.MutableOkHttp.$
  ```

**Comment by SuperMonster003** [comment]
en-US: Unfortunately, I have no clue about such problem. This issue is marked with labels "Helpless" and "Request For Help" for now.
zh-CN: 很遗憾, 我不知道如何处理这样的问题, 此议题暂时被标记为 "无法完成" 以及 "请求帮助".
