### ISSUE TITLE
部分文档上的示例报错

### ISSUE THREAD

**Issue by RFSN** [SuperMonster003/AutoJs6#188]
app.startActivity("console");
错误日志:
00:27:58.537/V: 开始运行 [$cwd/AAA.js [cache]].
00:27:58.611/E: Java 类 "org.autojs.autojs.runtime.api.AppUtils" 不存在名为 "__noSuchMethod__" 的公有访问字段或方法. (file:///android_asset/modules/__app__.js#277)
Java 类 "org.autojs.autojs.runtime.api.AppUtils" 不存在名为 "__noSuchMethod__" 的公有访问字段或方法.
    at file:///android_asset/modules/__app__.js:277:0
    at /data/user/0/org.autojs.autojs6/cache/tmp-scripts/tmp-1700411277881.js:3:0

00:27:58.617/V: [$cwd/AAA.js [cache]] 运行结束 (用时 0.069 秒)

**Comment by SuperMonster003** [comment]
感谢反馈, 将于下一版本修复上述问题.

_Sent from my XQ-DQ72 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
