### ISSUE TITLE
监控按键事件没反应

### ISSUE THREAD

**Issue by dddl18** [SuperMonster003/AutoJs6#283]
运行按键监听例子和自己按照文档中的写代码在按下的时候都没反应，执行的时候并没有报错，成功运行了，但是不会进入事件。

**Comment by TonyJiangWJ** [comment]
请问是HyperOS2吗，重启手机后是否还存在这个问题？
重启有效的话，重启过段时间是不是又有这个问题

**Comment by dddl18** [comment]
是的，我重启了看现在是可以正常触发事件了，还不知道过段时间是不是又有这个问题。用几天试试

**Comment by dddl18** [comment]
> 请问是HyperOS2吗，重启手机后是否还存在这个问题？ 重启有效的话，重启过段时间是不是又有这个问题

是的，重启过段时间又出现这个问题了，这个现在有解决方法吗？

**Comment by TonyJiangWJ** [comment]
有临时的解决办法，但是感觉这主要是系统的问题，代码不适合合并到AutoJS中。
原理是监听HyperOS2自身发送的按键广播，然后执行相应的操作。

**Comment by wengzhenquan** [comment]
Wrapped java.lang.SecurityException: org.autojs.autojs6: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts (/data/user/0/org.autojs.autojs6/cache/tmp-scripts/tmp-1743150526729.js#21)
Wrapped java.lang.SecurityException: org.autojs.autojs6: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
    at /data/user/0/org.autojs.autojs6/cache/tmp-scripts/tmp-1743150526729.js:21:0

**Comment by wengzhenquan** [comment]
> 这是一个演示，您可以在此基础上修改监听事件：
> 
> /*
>  * @Author: TonyJiangWJ
>  * @Date: 2024-12-31 14:56:33
>  * @Last Modified by: TonyJiangWJ
>  * @Last Modified time: 2025-01-03 17:07:18
>  * @Description: 按键广播监听DEMO
>  */
> 
> importPackage(android.content);
> 
> // 监听miui按键事件
> const ACTION = "miui.intent.action.KEYCODE_EXTERNAL"
> 
> let receiver = new JavaAdapter(android.content.BroadcastReceiver, {
>   onReceive: function (context, intent) {
>     if (ACTION == intent.getAction()) {
>       let event = intent.getParcelableExtra(Intent.EXTRA_KEY_EVENT);
>       if (event != null) {
>         // 提取keyCode
>         toastLog("Key pressed: " + event.getKeyCode());
>         // 这里添加你自己的代码，比如添加一个监听器什么的 根据keyCode做处理
>       }
>     }
>   }
> });
> 
> let filter = new IntentFilter();
> filter.addAction(ACTION);
> context.registerReceiver(receiver, filter);
> 
> setInterval(() => { }, 1000);
> 
> events.on("exit", function () {
>   console.log('注销receiver')
>   context.unregisterReceiver(receiver);
> })

Wrapped java.lang.SecurityException: org.autojs.autojs6: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts (/data/user/0/org.autojs.autojs6/cache/tmp-scripts/tmp-1743150526729.js#21)
Wrapped java.lang.SecurityException: org.autojs.autojs6: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
    at /data/user/0/org.autojs.autojs6/cache/tmp-scripts/tmp-1743150526729.js:21:0
