### ISSUE TITLE
请求postMultipart文件接口异常

### ISSUE THREAD

**Issue by 501658362** [SuperMonster003/AutoJs6#56]
大佬好，麻烦看看这个问题。调用以下上传图片接口报错了，上传图片到企业微信临时文件接口
```
function uploadImage(token, imgPath) {
    let url = "https://qyapi.weixin.qq.com/cgi-bin/media/upload?access_token=" + token + "&type=image";
    // 发送http请求
    http.postMultipart(url, {
        image: open(imgPath)
      },
      // 成功的回调函数
      function(res) {
        var result = res.body.json();
        toastLog("上传成功！结果：" + result);
      },
      // 失败的回调函数
      function(err) {
        toastLog("上传失败！错误信息：" + err);
      });
  }
```
报错信息 89行是postMultipart这个
```
18:05:56.377/E: TypeError: [JavaPackage org.autojs.pio.PFile] 是 object 而非函数. (file:///android_asset/modules/__http__.js#122)
TypeError: [JavaPackage org.autojs.pio.PFile] 是 object 而非函数.
    at file:///android_asset/modules/__http__.js:122:0
    at file:///android_asset/modules/__http__.js:108:0
    at file:///android_asset/modules/__http__.js:71:0
    at file:///android_asset/modules/__http__.js:158:0
    at file:///android_asset/modules/__http__.js:147:0
    at file:///android_asset/modules/__http__.js:177:0
    at uploadImage (/storage/emulated/0/脚本/微信推送.js:89:0)
    at sendWeiChat (/storage/emulated/0/脚本/微信推送.js:45:0)
    at /storage/emulated/0/脚本/微信推送.js:11:0
    ```

**Comment by SuperMonster003** [comment]
感谢反馈, 将于下一版本尝试修复上述问题.

**Comment by SuperMonster003** [comment]
v6.3.1 已尝试修复上述问题, 如问题复现, 可继续反馈.
