### ISSUE TITLE
Builk APK失败，改了好久还是不行请教应该怎么改？

### ISSUE THREAD

**Issue by hongfengfeiyang999** [SuperMonster003/AutoJs6#58]
Current platform: Android Studio Flamingo | 2022.2
Current classpath: com.android.tools.build:gradle:8.0.0

Execution failed for task ':app:kaptGenerateStubsDebugKotlin'.
> 'compileDebugJavaWithJavac' task (current target is 1.8) and 'kaptGenerateStubsDebugKotlin' task (current target is 19) jvm target compatibility should be set to the same Java version.

**Comment by SuperMonster003** [comment]
README.md 中有构建的详细步骤.  
如果依然有问题, 首先需确定你的 JDK 版本是否设置为 19+. 然后确保与构建项目相关文件 (如 build.gradle.kts 等) 代码保持其原始值 (除非明确了解修改项的意义).

**Comment by hongfengfeiyang999** [comment]
确实是jdk问题，已经下载jdk20，并重新clone到新文件夹（保持未做任何修改），重新bulid，出现两个错误
> Task :app:compileReleaseKotlin
w: file:///E:/androiddata/AutoJs6v2/app/src/main/java/org/autojs/autojs/core/web/InjectableWebView.kt:41:17 'setter for allowUniversalAccessFromFileURLs: Boolean' is deprecated. Deprecated in Java

> Task :app:compileReleaseJavaWithJavac FAILED
> Task :app:mergeReleaseJavaResource

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileReleaseJavaWithJavac'.
错误: 无效的源发行版：19

**Comment by SuperMonster003** [comment]
可参考以下文章中的解决方案.  
https://segmentfault.com/a/1190000023536478

**Comment by TKWei** [comment]
生成APK，一个提示错误都没有，安装后，还是启动不了。真机，模拟器都不行。一闪，就退出了。

**Comment by SuperMonster003** [comment]
@TKWei 可以提供一下 IDE 的 Logcat 标签页出现的相关异常信息.

**Comment by TKWei** [comment]
![搜狗截图20230606141933](https://github.com/SuperMonster003/AutoJs6/assets/22849062/d077e897-eb8b-4978-a38c-19afdbfb5dcf)

完整的：
2023-06-06 14:07:14.868 28057-28057 ActivityThread          org.autojs.autojs6                   W  handleWindowVisibility: no activity for token android.os.BinderProxy@83d2df0
2023-06-06 14:07:14.925 28057-28057 App                     org.autojs.autojs6                   D  setCurrentActivity: org.autojs.autojs.ui.splash.SplashActivity@34cb08
2023-06-06 14:07:14.939 28057-28057 App                     org.autojs.autojs6                   D  setCurrentActivity: org.autojs.autojs.ui.splash.SplashActivity@34cb08
2023-06-06 14:07:15.049 28057-28057 ActivityInfoProvider    org.autojs.autojs6                   D  setLatestComponent: org.autojs.autojs6/android.widget.FrameLayout org.autojs.autojs6/android.widget.FrameLayout
2023-06-06 14:07:15.127 28057-28057 ActivityInfoProvider    org.autojs.autojs6                   D  setLatestComponent: org.autojs.autojs6/org.autojs.autojs.ui.splash.SplashActivity org.autojs.autojs6/org.autojs.autojs.ui.splash.SplashActivity
2023-06-06 14:07:15.630 28057-28057 App                     org.autojs.autojs6                   D  setCurrentActivity: null
2023-06-06 14:07:15.639 28057-28057 ActivityThread          org.autojs.autojs6                   W  handleWindowVisibility: no activity for token android.os.BinderProxy@e54f814
2023-06-06 14:07:15.649 28057-28057 App                     org.autojs.autojs6                   D  setCurrentActivity: org.autojs.autojs.ui.main.MainActivity@3bc7275
2023-06-06 14:07:15.754 28057-28057 App                     org.autojs.autojs6                   D  setCurrentActivity: org.autojs.autojs.ui.main.MainActivity@3bc7275
2023-06-06 14:07:15.822 28057-28057 App                     org.autojs.autojs6                   D  setCurrentActivity: null
2023-06-06 14:07:15.836 28057-28057 System.err              org.autojs.autojs6                   W  java.net.ConnectException: Failed to connect to raw.githubusercontent.com/0.0.0.0:443
2023-06-06 14:07:15.836 28057-28057 System.err              org.autojs.autojs6                   W  	at okhttp3.internal.connection.ConnectPlan.connectSocket(ConnectPlan.kt:256)
2023-06-06 14:07:15.836 28057-28057 System.err              org.autojs.autojs6                   W  	at okhttp3.internal.connection.ConnectPlan.connectTcp(ConnectPlan.kt:128)
2023-06-06 14:07:15.836 28057-28057 System.err              org.autojs.autojs6                   W  	at okhttp3.internal.connection.FastFallbackExchangeFinder$launchTcpConnect$1.runOnce(FastFallbackExchangeFinder.kt:138)
2023-06-06 14:07:15.836 28057-28057 System.err              org.autojs.autojs6                   W  	at okhttp3.internal.concurrent.TaskRunner.runTask(TaskRunner.kt:117)
2023-06-06 14:07:15.836 28057-28057 System.err              org.autojs.autojs6                   W  	at okhttp3.internal.concurrent.TaskRunner.access$runTask(TaskRunner.kt:42)
2023-06-06 14:07:15.836 28057-28057 System.err              org.autojs.autojs6                   W  	at okhttp3.internal.concurrent.TaskRunner$runnable$1.run(TaskRunner.kt:66)
2023-06-06 14:07:15.836 28057-28057 System.err              org.autojs.autojs6                   W  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2023-06-06 14:07:15.836 28057-28057 System.err              org.autojs.autojs6                   W  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2023-06-06 14:07:15.836 28057-28057 System.err              org.autojs.autojs6                   W  	at java.lang.Thread.run(Thread.java:764)
2023-06-06 14:07:15.836 28057-28057 System.err              org.autojs.autojs6                   W  Caused by: java.net.ConnectException: failed to connect to localhost/127.0.0.1 (port 443) from /127.0.0.1 (port 51488) after 10000ms: isConnected failed: ECONNREFUSED (Connection refused)
2023-06-06 14:07:15.836 28057-28057 System.err              org.autojs.autojs6                   W  	at libcore.io.IoBridge.isConnected(IoBridge.java:278)
2023-06-06 14:07:15.836 28057-28057 System.err              org.autojs.autojs6                   W  	at libcore.io.IoBridge.connectErrno(IoBridge.java:187)
2023-06-06 14:07:15.836 28057-28057 System.err              org.autojs.autojs6                   W  	at libcore.io.IoBridge.connect(IoBridge.java:129)
2023-06-06 14:07:15.836 28057-28057 System.err              org.autojs.autojs6                   W  	at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:137)
2023-06-06 14:07:15.836 28057-28057 System.err              org.autojs.autojs6                   W  	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
2023-06-06 14:07:15.836 28057-28057 System.err              org.autojs.autojs6                   W  	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:228)
2023-06-06 14:07:15.836 28057-28057 System.err              org.autojs.autojs6                   W  	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
2023-06-06 14:07:15.836 28057-28057 System.err              org.autojs.autojs6                   W  	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
2023-06-06 14:07:15.836 28057-28057 System.err              org.autojs.autojs6                   W  	at java.net.Socket.connect(Socket.java:621)
2023-06-06 14:07:15.836 28057-28057 System.err              org.autojs.autojs6                   W  	at okhttp3.internal.platform.AndroidPlatform.connectSocket(AndroidPlatform.kt:60)
2023-06-06 14:07:15.836 28057-28057 System.err              org.autojs.autojs6                   W  	at okhttp3.internal.connection.ConnectPlan.connectSocket(ConnectPlan.kt:254)
2023-06-06 14:07:15.836 28057-28057 System.err              org.autojs.autojs6                   W  	... 8 more
2023-06-06 14:07:15.836 28057-28057 System.err              org.autojs.autojs6                   W  Caused by: android.system.ErrnoException: isConnected failed: ECONNREFUSED (Connection refused)
2023-06-06 14:07:15.836 28057-28057 System.err              org.autojs.autojs6                   W  	at libcore.io.IoBridge.isConnected(IoBridge.java:267)
2023-06-06 14:07:15.836 28057-28057 System.err              org.autojs.autojs6                   W  	... 18 more
2023-06-06 14:07:15.957 28057-28057 ActivityInfoProvider    org.autojs.autojs6                   D  setLatestComponent: org.autojs.autojs6/com.afollestad.materialdialogs.MaterialDialog org.autojs.autojs6/com.afollestad.materialdialogs.MaterialDialog
2023-06-06 14:07:16.010 28057-28057 ActivityInfoProvider    org.autojs.autojs6                   D  setLatestComponent: com.android.launcher3/com.android.launcher3.launcher3.Launcher com.android.launcher3/com.android.launcher3.launcher3.Launcher
2023-06-06 14:07:16.031 28057-28057 ActivityInfoProvider    org.autojs.autojs6                   D  setLatestComponent: com.android.launcher3/com.android.launcher3.launcher3.Launcher com.android.launcher3/com.android.launcher3.launcher3.Launcher
2023-06-06 14:07:16.072 28057-28057 EventBus                org.autojs.autojs6                   W  Subscriber to unregister was not registered before: class org.autojs.autojs.ui.main.MainActivity
2023-06-06 14:07:16.073 28057-28057 WindowManager           org.autojs.autojs6                   E  
                                                                                                    android.view.WindowLeaked: Activity org.autojs.autojs.ui.main.MainActivity has leaked window DecorView@d53533d[MainActivity] that was originally added here
                                                                                                    	at android.view.ViewRootImpl.<init>(ViewRootImpl.java:511)
                                                                                                    	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:346)
                                                                                                    	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
                                                                                                    	at android.app.Dialog.show(Dialog.java:329)
                                                                                                    	at com.afollestad.materialdialogs.MaterialDialog.show(MaterialDialog.java:464)
                                                                                                    	at com.afollestad.materialdialogs.MaterialDialog$Builder.show(MaterialDialog.java:2189)
                                                                                                    	at org.autojs.autojs.ui.common.NotAskAgainDialog$Builder.show(NotAskAgainDialog.java:40)
                                                                                                    	at org.autojs.autojs.permission.DisplayOverOtherAppsPermission.urge(DisplayOverOtherAppsPermission.kt:77)
                                                                                                    	at org.autojs.autojs.permission.DisplayOverOtherAppsPermission.urgeIfNeeded(DisplayOverOtherAppsPermission.kt:81)
                                                                                                    	at org.autojs.autojs.ui.main.MainActivity.onCreate(MainActivity.kt:110)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:7146)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:7137)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loop(Looper.java:193)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:6669)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:533)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:861)

**Comment by SuperMonster003** [comment]
6.4.1 已针对构建脚本的智能化进行了多次优化, 如仍有相关问题, 可继续反馈.

此 issue 暂时关闭.
