### ISSUE TITLE
打包应用功能失效

### ISSUE THREAD

**Issue by bcmdy** [SuperMonster003/AutoJs6#77]
打包应用功能失效，随便打包个例子脚本，安装打开报错，目测脚本解密失败
`11:00:19.900/E: illegal character
- - - - - - - - - - -

org.mozilla.javascript.EvaluatorException: illegal character (main.js#1)
	at org.mozilla.javascript.DefaultErrorReporter.runtimeError(DefaultErrorReporter.java:77)
	at org.mozilla.javascript.DefaultErrorReporter.error(DefaultErrorReporter.java:64)
	at org.mozilla.javascript.Parser.addError(Parser.java:254)
	at org.mozilla.javascript.Parser.addError(Parser.java:232)
	at org.mozilla.javascript.Parser.addError(Parser.java:228)
	at org.mozilla.javascript.TokenStream.getToken(TokenStream.java:1026)
	at org.mozilla.javascript.Parser.peekToken(Parser.java:395)
	at org.mozilla.javascript.Parser.name(Parser.java:3129)
	at org.mozilla.javascript.Parser.primaryExpr(Parser.java:3019)
	at org.mozilla.javascript.Parser.memberExpr(Parser.java:2631)
	at org.mozilla.javascript.Parser.unaryExpr(Parser.java:2529)
	at org.mozilla.javascript.Parser.mulExpr(Parser.java:2454)
	at org.mozilla.javascript.Parser.addExpr(Parser.java:2438)
	at org.mozilla.javascript.Parser.shiftExpr(Parser.java:2419)
	at org.mozilla.javascript.Parser.relExpr(Parser.java:2394)
	at org.mozilla.javascript.Parser.eqExpr(Parser.java:2366)
	at org.mozilla.javascript.Parser.bitAndExpr(Parser.java:2355)
	at org.mozilla.javascript.Parser.bitXorExpr(Parser.java:2344)
	at org.mozilla.javascript.Parser.bitOrExpr(Parser.java:2333)
	at org.mozilla.javascript.Parser.andExpr(Parser.java:2322)
	at org.mozilla.javascript.Parser.orExpr(Parser.java:2311)
	at org.mozilla.javascript.Parser.condExpr(Parser.java:2275)
	at org.mozilla.javascript.Parser.assignExpr(Parser.java:2238)
	at org.mozilla.javascript.Parser.expr(Parser.java:2217)
	at org.mozilla.javascript.Parser.nameOrLabel(Parser.java:1970)
	at org.mozilla.javascript.Parser.statementHelper(Parser.java:1229)
	at org.mozilla.javascript.Parser.statement(Parser.java:1098)
	at org.mozilla.javascript.Parser.parse(Parser.java:642)
	at org.mozilla.javascript.Parser.parse(Parser.java:601)
	at org.mozilla.javascript.Context.compileImpl(Context.java:2514)
	at org.mozilla.javascript.Context.compileReader(Context.java:1458)
	at org.mozilla.javascript.Context.compileReader(Context.java:1430)
	at org.mozilla.javascript.Context.evaluateReader(Context.java:1272)
	at com.stardust.autojs.engine.RhinoJavaScriptEngine.doExecution(RhinoJavaScriptEngine.java:77)
	at com.stardust.autojs.engine.JavaScriptEngine.execute(JavaScriptEngine.java:22)
	at com.stardust.autojs.engine.LoopBasedJavaScriptEngine.access$001(LoopBasedJavaScriptEngine.java:18)
	at com.stardust.autojs.engine.LoopBasedJavaScriptEngine.lambda$execute$0$LoopBasedJavaScriptEngine(LoopBasedJavaScriptEngine.java:43)
	at com.stardust.autojs.engine.LoopBasedJavaScriptEngine$$Lambda$0.run(Unknown Source:6)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at com.stardust.autojs.engine.LoopBasedJavaScriptEngine.execute(LoopBasedJavaScriptEngine.java:59)
	at com.stardust.autojs.engine.LoopBasedJavaScriptEngine.execute(LoopBasedJavaScriptEngine.java:35)
	at com.stardust.autojs.execution.LoopedBasedJavaScriptExecution.doExecution(LoopedBasedJavaScriptExecution.java:42)
	at com.stardust.autojs.execution.RunnableScriptExecution.execute(RunnableScriptExecution.java:38)
	at com.stardust.autojs.execution.RunnableScriptExecution.execute(RunnableScriptExecution.java:32)
	at com.stardust.autojs.execution.RunnableScriptExecution.run(RunnableScriptExecution.java:27)
	at java.lang.Thread.run(Thread.java:1012)`

**Comment by SuperMonster003** [comment]
> @SuperMonster003 直接修改比较困难，只能尝试用变通的方法实现了一个打包的简易版本，虽然不太成熟，大佬还是可以参考一下，希望AutoJs6未来能有更加完善的打包功能： [AutoJs6v6.3.3pre打包测试以及适用于AutoJs6v6.3.3pre的打包模板文件](https://github.com/LZX284/AutoJs6/releases/tag/v6.3.3pre)

如果能将打包功能内置到应用中, 避免安装额外的打包插件, 那还是蛮不错的.  
看到你的 Fork 项目中已经基本实现了打包功能内置, 后期完善后, 欢迎随时提交 PR. :)

**Comment by SuperMonster003** [comment]
> @SuperMonster003 真的不考虑对打包应用做进一步开发, 甚至可能永久搁置吗？ 最近两个月各种安卓自动化的项目试了一溜十三道（uiautomator2、airtest，AutoXjs、EasyClick），直到前天才在一个群里听别人提起Autojs6这个项目，试了一下，马上就切换过来了，真好用，唯一遗憾的打包应用差点意思。

是的, 打包功能我是基本不会考虑继续开发的.

即便如此, 依然有其他基于 Auto.js 4.1.1 alpha2 开发的优秀开源版本可供使用. :)

**Comment by buli666** [comment]
没办法打包apk最新版的 大佬要怎么搞 @SuperMonster003
