### ISSUE TITLE
建议增加本地OCR功能

### ISSUE THREAD

**Issue by a4youma** [SuperMonster003/AutoJs6#8]
谢谢SuperMonster003继续开发。希望增加OCR功能，具体请参考https://github.com/PaddlePaddle/PaddleOCR，以及https://github.com/hamibot/hamibot

**Comment by lnxcyq** [comment]
怎么开发者也不采纳一下

**Comment by SuperMonster003** [comment]
能力有限, 目前还无法完成上述功能开发, 此 issue 暂时标记为无法完成.

**Comment by SuperMonster003** [comment]
已于 [v6.3.0](https://github.com/SuperMonster003/AutoJs6/releases/tag/v6.3.0) 增加基于 Google MLKit 的简单 OCR 功能.  
试用后如有相关问题或建议, 可于此处反馈或提交新的 `议题 (Issue)` 反馈.

**Comment by jia20210510** [comment]
调用OCR识图时autojs6程序会崩溃然后自动重启

**Comment by rootbootsyy** [comment]
orc识图可以获取每一个文本坐标吗

**Comment by SuperMonster003** [comment]
@jia20210510 6.4.1 是否依然存在此问题
@rootbootsyy 可以的, 参阅应用文档.

**Comment by lcydtc15967073371** [comment]
> 调用OCR识图时autojs6程序会崩溃然后自动重启

我也一样

**Comment by SuperMonster003** [comment]
> 调用OCR识图时autojs6程序会崩溃然后自动重启

@jia20210510 @lcydtc15967073371 
目前最新版本 (6.6.4) 是否依然存在上述异常.
如果依然存在, 请提供关键代码片段以便排查问题.

**Comment by beartom** [comment]
> > 调用OCR识图时autojs6程序会崩溃然后自动重启
> 
> [@jia20210510](https://github.com/jia20210510) [@lcydtc15967073371](https://github.com/lcydtc15967073371) 目前最新版本 (6.6.4) 是否依然存在上述异常. 如果依然存在, 请提供关键代码片段以便排查问题.

在模拟器环境能重现，不确定是否和之前原因相同。不论打包应用运行还是直接运行脚本，使用ML Kit模式时程序崩溃，使用Paddle模式正常。红米Note 11Pro真机运行正常。


测试环境： 
Mumu模拟器V4.1.31(3724) 
Andriod版本12

测试脚本：
```js
images.requestScreenCapture();
sleep(5000)

let img = images.captureScreen();
var results = ocr.detect(img);
results.forEach(o => console.info(o))
exit()
```
模拟器日志
[mumu_log1.txt](https://github.com/user-attachments/files/21428435/mumu_log1.txt)
程序dump
[10042.log](https://github.com/user-attachments/files/21428434/10042.log)


好像是libmlkit_google_ocr_pipeline.so动态库引起的

**Comment by SuperMonster003** [comment]
@beartom 

日志中,

```text
--------- beginning of crash
FATAL EXCEPTION: main
Process: org.autojs.autojs6, PID: 1720
java.lang.RuntimeException: Unable to get provider com.google.mlkit.common.internal.MlKitInitProvider: java.lang.IllegalStateException: MlKitContext is already initialized
	at android.app.ActivityThread.installProvider(ActivityThread.java:7654)
	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7166)
	at android.app.ActivityThread.handleInstallProvider(ActivityThread.java:4152)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2261)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:8060)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1091)
Caused by: java.lang.IllegalStateException: MlKitContext is already initialized
	at com.google.android.gms.common.internal.Preconditions.checkState(com.google.android.gms:play-services-basement@@18.3.0:2)
	at com.google.mlkit.common.sdkinternal.MlKitContext.zzb(com.google.mlkit:common@@18.11.0:1)
	at com.google.mlkit.common.sdkinternal.MlKitContext.zza(com.google.mlkit:common@@18.11.0:1)
	at com.google.mlkit.common.internal.MlKitInitProvider.onCreate(com.google.mlkit:common@@18.11.0:3)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2410)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2380)
	at com.google.mlkit.common.internal.MlKitInitProvider.attachInfo(com.google.mlkit:common@@18.11.0:3)
	at android.app.ActivityThread.installProvider(ActivityThread.java:7649)
	... 10 more
```

可以看出, MlKit 上下文重复初始化导致了异常, 而且堆栈指向 `com.google.mlkit.common.internal.MlKitInitProvider`.

我尝试询问了 JetBrains AI Assistant (o3), 部分内容如下:

> MlKit 内部用一个静态标志位判断是否已初始化, 若再次调用就抛出上面的异常.
> 在多数设备上, 系统只会为同一个 `<provider>` 创建一次实例, 但有些系统因为一些特性 (多 APK 拆分 / splitCompat / 双 AAR 版本并存) 会让 Android Framework 认为还有另一份带不同 authority 的 MlKitInitProvider 存在, 于是尝试第二次 attach, 便触发了重复初始化异常.

因此思路可以是禁用 MlKit 官方的 Provider, 并在项目中显式初始化:

```xml
<manifest>
    <application>
        <provider
            android:name="com.google.mlkit.common.internal.MlKitInitProvider"
            android:authorities="${applicationId}.mlkitinitprovider"
            tools:node="remove" />
    </application>
</manifest>
```

```kt
class App : MultiDexApplication() {

    override fun onCreate() {
        super.onCreate()
        initMlKitContext()
    }

    private fun initMlKitContext() {
        ApkBuilder.Libs.MLKIT_OCR.ensureLibFiles(Ocr.Companion.OcrMode.MLKIT.value)
        MlKitContext.initializeIfNeeded(this)
    }

}
```
