### ISSUE TITLE
Error on update to new version (

### ISSUE THREAD

**Issue by anhnhoktvn** [SuperMonster003/AutoJs6#91]
It used to work fine with older version. After upgrading, I got an error
````

java.lang.Exception: Unknown data type (0) for message dispatching
	at org.autojs.autojs.runtime.ScriptRuntime.popException(ScriptRuntime.java:84)
	at org.autojs.autojs.pluginclient.JsonSocket.onMessageDispatch(JsonSocket.java:221)
	at org.autojs.autojs.pluginclient.JsonSocket.onMessageDispatch(JsonSocket.java:225)
	at org.autojs.autojs.pluginclient.JsonSocket.lambda$monitorMessage$0(JsonSocket.java:331)
	at org.autojs.autojs.pluginclient.JsonSocket.$r8$lambda$va2cxRhe8N9XY6l6jBcuYwu6HoA(Unknown Source:0)
	at org.autojs.autojs.pluginclient.JsonSocket$$ExternalSyntheticLambda0.run(Unknown Source:6)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
19:24:40.523/E: Unknown data type (0) for message dispatching

java.lang.Exception: Unknown data type (0) for message dispatching
	at org.autojs.autojs.runtime.ScriptRuntime.popException(ScriptRuntime.java:84)
	at org.autojs.autojs.pluginclient.JsonSocket.onMessageDispatch(JsonSocket.java:221)
	at org.autojs.autojs.pluginclient.JsonSocket.onMessageDispatch(JsonSocket.java:225)
	at org.autojs.autojs.pluginclient.JsonSocket.onMessageDispatch(JsonSocket.java:225)
	at org.autojs.autojs.pluginclient.JsonSocket.lambda$monitorMessage$0(JsonSocket.java:331)
	at org.autojs.autojs.pluginclient.JsonSocket.$r8$lambda$va2cxRhe8N9XY6l6jBcuYwu6HoA(Unknown Source:0)
	at org.autojs.autojs.pluginclient.JsonSocket$$ExternalSyntheticLambda0.run(Unknown Source:6)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
19:24:40.528/E: Unknown data type (0) for message dispatching

java.lang.Exception: Unknown data type (0) for message dispatching
	at org.autojs.autojs.runtime.ScriptRuntime.popException(ScriptRuntime.java:84)
	at org.autojs.autojs.pluginclient.JsonSocket.onMessageDispatch(JsonSocket.java:221)
	at org.autojs.autojs.pluginclient.JsonSocket.onMessageDispatch(JsonSocket.java:225)
	at org.autojs.autojs.pluginclient.JsonSocket.onMessageDispatch(JsonSocket.java:225)
	at org.autojs.autojs.pluginclient.JsonSocket.onMessageDispatch(JsonSocket.java:225)
	at org.autojs.autojs.pluginclient.JsonSocket.lambda$monitorMessage$0(JsonSocket.java:331)
	at org.autojs.autojs.pluginclient.JsonSocket.$r8$lambda$va2cxRhe8N9XY6l6jBcuYwu6HoA(Unknown Source:0)
	at org.autojs.autojs.pluginclient.JsonSocket$$ExternalSyntheticLambda0.run(Unknown Source:6)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
19:24:40.533/E: Unknown data type (0) for message dispatching

````

**Comment by SuperMonster003** [comment]
I've attempted to fix the above issue in AutoJs6 v6.3.3.
Feel free to let me know if the problem persists after trying out the new version.
Thanks for the feedback.

BTW, the VSCode extension needs to be upgraded to at least v1.0.6.
