### ISSUE TITLE
vs Code 编辑后保存到设备时有问题

### ISSUE THREAD

**Issue by CuteLicense** [SuperMonster003/AutoJs6#92]
版本 ：v6.3.2 （6.3.1 正常）

1、手机提示保存成功，但没有更新文件，而是多出了
 **extension - output -003.autojs6- vsc ode - ext -#1- Channel for (手机型号(192.168.1.js**
文件
2、直接到电脑上运行脚本时，出现一堆错误，诸如：
at org.autojs.autojs.pluginclient.JsonSocket.onMessageDispatch(JsonSocket.java:225)
	at org.autojs.autojs.pluginclient.JsonSocket.lambda$monitorMessage$0(JsonSocket.java:331)
	at org.autojs.autojs.pluginclient.JsonSocket.$r8$lambda$va2cxRhe8N9XY6l6jBcuYwu6HoA(Unknown Source:0)
	at org.autojs.autojs.pluginclient.JsonSocket$$ExternalSyntheticLambda0.run(Unknown Source:6)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1033)
10:29:52.105/E: Unknown data type (0) for message dispatching

java.lang.Exception: Unknown data type (0) for message dispatching
	at org.autojs.autojs.runtime.ScriptRuntime.popException(ScriptRuntime.java:84)
	at org.autojs.autojs.pluginclient.JsonSocket.onMessageDispatch(JsonSocket.java:221)
	at org.autojs.autojs.pluginclient.JsonSocket.onMessageDispatch(JsonSocket.java:225)
	at org.autojs.autojs.pluginclient.JsonSocket.onMessageDispatch(JsonSocket.java:225)
	at org.autojs.autojs.pluginclient.JsonSocket.onMessageDispatch(JsonSocket.java:225)

**Comment by hongfengfeiyang999** [comment]
我也是一样，这版本有比较大的bug呀

**Comment by lifugan96** [comment]
我也遇到了，可以运行的代码，增加一个空的方法之后报错，或者增加几行注释也是同样的错误。

**Comment by SuperMonster003** [comment]
#91
