### ISSUE TITLE
BUG . 使用悬浮窗时，出现递归查找loadClass，导致栈溢出

### ISSUE THREAD

**Issue by RFSN** [SuperMonster003/AutoJs6#99]
部分日志如下：
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:216)
2023-07-13 00:43:19.301 16270-16270 System.err              org.autojs.autojs6                   W  	at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:211)
2023-07-13 00:43:19.301 16270-16270 System.err              org.autojs.autojs6                   W  	at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1869)
2023-07-13 00:43:19.301 16270-16270 System.err              org.autojs.autojs6                   W  	at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:1051)
2023-07-13 00:43:19.301 16270-16270 System.err              org.autojs.autojs6                   W  	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:87)
2023-07-13 00:43:19.301 16270-16270 System.err              org.autojs.autojs6                   W  	at org.mozilla.javascript.InterfaceAdapter.invokeImpl(InterfaceAdapter.java:157)
2023-07-13 00:43:19.301 16270-16270 System.err              org.autojs.autojs6                   W  	at org.mozilla.javascript.VMBridge_custom$InterfaceAdapterWrapper.invokeImpl(VMBridge_custom.java:153)
2023-07-13 00:43:19.301 16270-16270 System.err              org.autojs.autojs6                   W  	at org.mozilla.javascript.VMBridge_custom$InterfaceAdapterWrapper.lambda$invoke$0(VMBridge_custom.java:136)
2023-07-13 00:43:19.301 16270-16270 System.err              org.autojs.autojs6                   W  	at org.mozilla.javascript.VMBridge_custom$InterfaceAdapterWrapper.$r8$lambda$GM2BaIWLqJsbHoNPr8Zc4jy_3KI(Unknown Source:0)
2023-07-13 00:43:19.301 16270-16270 System.err              org.autojs.autojs6                   W  	at org.mozilla.javascript.VMBridge_custom$InterfaceAdapterWrapper$$ExternalSyntheticLambda0.run(Unknown Source:13)
2023-07-13 00:43:19.301 16270-16270 System.err              org.autojs.autojs6                   W  	at org.mozilla.javascript.VMBridge_custom$InterfaceAdapterWrapper.call(VMBridge_custom.java:145)
2023-07-13 00:43:19.301 16270-16270 System.err              org.autojs.autojs6                   W  	at org.mozilla.javascript.VMBridge_custom$InterfaceAdapterWrapper.invoke(VMBridge_custom.java:137)
2023-07-13 00:43:19.301 16270-16270 System.err              org.autojs.autojs6                   W  	at org.mozilla.javascript.VMBridge_custom.lambda$newInterfaceProxy$0(VMBridge_custom.java:57)
2023-07-13 00:43:19.301 16270-16270 System.err              org.autojs.autojs6                   W  	at org.mozilla.javascript.VMBridge_custom.$r8$lambda$fNOSBEVMPkNsq5y7_94AYDUfqVA(Unknown Source:0)
2023-07-13 00:43:19.301 16270-16270 System.err              org.autojs.autojs6                   W  	at org.mozilla.javascript.VMBridge_custom$$ExternalSyntheticLambda0.invoke(Unknown Source:15)
2023-07-13 00:43:19.301 16270-16270 System.err              org.autojs.autojs6                   W  	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
2023-07-13 00:43:19.301 16270-16270 System.err              org.autojs.autojs6                   W  	at $Proxy8.inflateWindowView(Unknown Source)
2023-07-13 00:43:19.301 16270-16270 System.err              org.autojs.autojs6                   W  	at org.autojs.autojs.core.floaty.RawWindow.<init>(RawWindow.kt:35)
2023-07-13 00:43:19.301 16270-16270 System.err              org.autojs.autojs6                   W  	at org.autojs.autojs.runtime.api.Floaty$JsRawWindow.<init>(Floaty.kt:92)
2023-07-13 00:43:19.301 16270-16270 System.err              org.autojs.autojs6                   W  	at org.autojs.autojs.runtime.api.Floaty.rawWindow(Floaty.kt:53)
2023-07-13 00:43:19.301 16270-16270 System.err              org.autojs.autojs6                   W  	at java.lang.reflect.Method.invoke(Native Method)

at java.lang.ClassLoader.loadClass(ClassLoader.java:367)
2023-07-13 00:41:08.914 15908-15908 System.err              org.autojs.autojs6                   W  	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
2023-07-13 00:41:08.914 15908-15908 System.err              org.autojs.autojs6                   W  	at org.autojs.autojs.rhino.AndroidClassLoader.loadClass(AndroidClassLoader.kt:103)
2023-07-13 00:41:08.914 15908-15908 System.err              org.autojs.autojs6                   W  	at java.lang.ClassLoader.loadClass(ClassLoader.java:367)
2023-07-13 00:41:08.914 15908-15908 System.err              org.autojs.autojs6                   W  	at org.autojs.autojs.rhino.AndroidClassLoader.loadClass(AndroidClassLoader.kt:103)
2023-07-13 00:41:08.915 15908-15908 System.err              org.autojs.autojs6                   W  	at org.autojs.autojs.rhino.AndroidClassLoader.loadClass(AndroidClassLoader.kt:103)
2023-07-13 00:41:08.915 15908-15908 System.err              org.autojs.autojs6                   W  	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
2023-07-13 00:41:08.915 15908-15908 System.err              org.autojs.autojs6                   W  	at org.autojs.autojs.rhino.AndroidClassLoader.loadClass(AndroidClassLoader.kt:103)
2023-07-13 00:41:08.915 15908-15908 System.err              org.autojs.autojs6                   W  	at java.lang.ClassLoader.loadClass(ClassLoader.java:367)
2023-07-13 00:41:08.916 15908-15908 System.err              org.autojs.autojs6                   W  	at java.lang.ClassLoader.loadClass(ClassLoader.java:367)
2023-07-13 00:41:08.916 15908-15908 System.err              org.autojs.autojs6                   W  	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
2023-07-13 00:41:08.916 15908-15908 System.err              org.autojs.autojs6                   W  	at org.autojs.autojs.rhino.AndroidClassLoader.loadClass(AndroidClassLoader.kt:103)
2023-07-13 00:41:08.916 15908-15908 System.err              org.autojs.autojs6                   W  	at java.lang.ClassLoader.loadClass(ClassLoader.java:367)
2023-07-13 00:41:08.916 15908-15908 System.err              org.autojs.autojs6                   W  	at org.autojs.autojs.rhino.AndroidClassLoader.loadClass(AndroidClassLoader.kt:103)
2023-07-13 00:41:08.916 15908-15908 System.err              org.autojs.autojs6                   W  	at java.lang.ClassLoader.loadClass(ClassLoader.java:367)
2023-07-13 00:41:08.916 15908-15908 chatty                  org.autojs.autojs6                   I  uid=10278(org.autojs.autojs6) identical 2 lines
2023-07-13 00:41:08.916 15908-15908 System.err              org.autojs.autojs6                   W  	at java.lang.ClassLoader.loadClass(ClassLoader.java:367)
2023-07-13 00:41:08.916 15908-15908 System.err              org.autojs.autojs6                   W  	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
2023-07-13 00:41:08.917 15908-15908 System.err              org.autojs.autojs6                   W  	at org.autojs.autojs.rhino.AndroidClassLoader.loadClass(AndroidClassLoader.kt:103)
2023-07-13 00:41:08.917 15908-15908 System.err              org.autojs.autojs6                   W  	at java.lang.ClassLoader.loadClass(ClassLoader.java:367)
2023-07-13 00:41:08.917 15908-15908 System.err              org.autojs.autojs6                   W  	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
2023-07-13 00:41:08.917 15908-15908 System.err              org.autojs.autojs6                   W  	at org.autojs.autojs.rhino.AndroidClassLoader.loadClass(AndroidClassLoader.kt:103)
2023-07-13 00:41:08.917 15908-15908 System.err              org.autojs.autojs6                   W  	at java.lang.ClassLoader.loadClass(ClassLoader.java:367)
2023-07-13 00:41:08.917 15908-15908 System.err              org.autojs.autojs6                   W  	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
2023-07-13 00:41:08.917 15908-15908 System.err              org.autojs.autojs6                   W  	at org.autojs.autojs.rhino.AndroidClassLoader.loadClass(AndroidClassLoader.kt:103)
2023-07-13 00:41:08.918 15908-15908 System.err              org.autojs.autojs6                   W  	at org.autojs.autojs.rhino.AndroidClassLoader.loadClass(AndroidClassLoader.kt:103)
2023-07-13 00:41:08.918 15908-15908 System.err              org.autojs.autojs6                   W  	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
2023-07-13 00:41:08.918 15908-15908 System.err              org.autojs.autojs6                   W  	at java.lang.ClassLoader.loadClass(ClassLoader.java:367)

**Comment by RFSN** [comment]
同样的代码，在6.3.1 版本上，虽然布局会有些错乱，但是至少可以运行的，但是在6.3.2 会直接栈溢出

**Comment by SuperMonster003** [comment]
请提供一下导致上述异常的示例代码或代码片段.

_Sent from my XQ-DQ72 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by RFSN** [comment]
有没有群，或者联系方式，因为那个代码也是别的群友发给我的，不是我自己写的，如果贴在公共区域可能不是很好。

**Comment by SuperMonster003** [comment]
https://github.com/SuperMonster003/AutoJs6/issues/36#issuecomment-1536945921

**Comment by SuperMonster003** [comment]
6.3.3 已尝试修复上述问题, 使用后如问题复现, 可继续反馈.
